language: python

sudo: false

matrix:
  include:
    - python: 3.5.0
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27

install:
  - pip install -U tox pytest-cov

script:
  - tox

before_install:
  - pip install pytest-cov codecov -r tests/requirements.txt

after_success:
  - py.test tests/ --cov=./
  - codecov