language: python

sudo: false

matrix:
  include:
    - python: 3.5.0
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27


install:
  - pip install -U tox

script:
  - tox